#!/usr/bin/env python3
"""ArcForges delivery graph tool: validate, generate views, analyse and query readiness.

The authoritative scheduling data is Design `docs/planning/delivery/delivery-graph.json`
(decision P2-018, rules in Design `docs/planning/delivery/README.md`). Every Markdown view in
Design and Plan's `list.md` is generated from that one file; hand edits to generated regions are
overwritten and detected by `check`.

Commands (standard library only; documentation tooling, not a scheduler):
  python tools/delivery.py check     [--design PATH] [--plan PATH]
  python tools/delivery.py generate  [--design PATH] [--plan PATH]
  python tools/delivery.py analyze   [--design PATH] [--workers 1,4,8,16,32]
  python tools/delivery.py ready     [--design PATH] [--plan PATH] [--lane LANE]

`ready` lists tasks whose start prerequisites are complete according to Plan `ledger/tasks/*.md`;
it reads files only and never assigns, claims or starts work.
"""
from __future__ import annotations

import argparse
import heapq
import json
import re
import sys
from collections import Counter, defaultdict, deque
from pathlib import Path

PLAN_ROOT = Path(__file__).resolve().parents[1]
GRAPH_REL = 'docs/planning/delivery/delivery-graph.json'
DELIVERY_REL = 'docs/planning/delivery'
WP_REL = 'docs/planning/work-packages'
TASK_ID = re.compile(r'^[A-Z]{2,6}\.\d{2}$')
SUB_ID = re.compile(r'^SUB-[a-z0-9]+(?:-[a-z0-9]+)*$')
RES_ID = re.compile(r'^RES-[a-z0-9]+(?:-[a-z0-9]+)*$')
POB_ID = re.compile(r'^WP-(\d{2}):[a-z0-9]+(?:-[a-z0-9]+)*$')
SUBSTEP = re.compile(r'^WP-(\d{2})\.(\d{2})$')
DECISION = re.compile(r'^P2-\d{3}$')
START_TYPES = {'contract', 'artifact', 'design', 'release'}
COMPLETE_TYPES = {'integration'}
KINDS = {'governance', 'contract', 'producer', 'feature', 'service', 'proof', 'integration',
         'acceptance', 'release', 'adoption'}
SIZES = {'S': 1, 'M': 2, 'L': 4, 'XL': 8}
BASELINE = {'accepted', 'reported-unverified', 'not-started'}
MODES = {'append', 'exclusive', 'read', 'regenerate'}
# Corpus identifier grammar used by DesktopPlatform eng/design_corpus.py; every occurrence in a
# generated Design view must be a link to its defining anchor.
CORPUS_ID = re.compile(r'(?<![\w-])(?:WP-\d{2}(?:\.\d{2})?|P2-\d{3}|F-[A-Z]{2}-[1-9]\d*|'
                       r'[A-Z][A-Z0-9]{0,5}-(?:[A-Z]\d{1,3}|\d{2,3}[a-z]?))(?![\w-]|\.\d)')
LINK = re.compile(r'\[([^\]\n]+)\]\(([^)\n]+)\)')
ANCHOR = re.compile(r'<a\s+id="([^"]+)"\s*>\s*</a>')
BEGIN = '<!-- delivery-graph:begin (generated by Plan tools/delivery.py; do not edit) -->'
END = '<!-- delivery-graph:end -->'


class Fail(Exception):
    pass


def slug(task_id: str) -> str:
    return 'task-' + task_id.lower().replace('.', '-')


def load_json(path: Path):
    def hook(pairs):
        out = {}
        for k, v in pairs:
            if k in out:
                raise Fail(f'duplicate JSON key {k} in {path}')
            out[k] = v
        return out
    return json.loads(path.read_text(encoding='utf-8'), object_pairs_hook=hook)


# ----------------------------------------------------------------------------------------------
# Design corpus inputs
# ----------------------------------------------------------------------------------------------

def wp_files(design: Path) -> dict[str, Path]:
    files = {}
    for p in sorted((design / WP_REL).glob('[0-9][0-9]-*.md')):
        files[p.name[:2]] = p
    return files


def substeps(design: Path) -> dict[str, dict]:
    """Every active numbered substep, parsed from the obligation catalogue headings."""
    out = {}
    for wp, p in wp_files(design).items():
        for line in p.read_text(encoding='utf-8').splitlines():
            m = re.match(r'^### WP-(\d{2})\.(\d{2}) — (.+?)\s*$', line)
            if m:
                sid = f'WP-{m[1]}.{m[2]}'
                out[sid] = {'id': sid, 'wp': m[1], 'title': m[3].rstrip('.'), 'file': p.name}
    return out


def anchor_homes(design: Path) -> dict[str, list[str]]:
    """Map rule identifiers to the documents that define `rule-<id>` anchors."""
    homes = defaultdict(list)
    for p in sorted((design / 'docs').rglob('*.md')):
        rel = p.relative_to(design).as_posix()
        if rel.startswith('docs/deprecated-inputs/') and not rel.endswith('README.md'):
            continue
        for a in ANCHOR.findall(p.read_text(encoding='utf-8')):
            if a.startswith('rule-'):
                homes[a[5:]].append(rel)
    return homes


PREFERRED_HOMES = [
    'docs/decisions/phase-2-specification-decisions.md',
    'docs/decisions/phase-1-foundation-decisions.md',
    'docs/assurance/open-gates-register.md',
    'docs/assurance/release-gates.md',
    'docs/requirements/01-normative-glossary-and-invariants.md',
    'docs/planning/implementation-sequence.md',
    'docs/planning/delivery/README.md',
]


class Linker:
    def __init__(self, design: Path, from_rel: str):
        self.design = design
        self.from_dir = str(Path(from_rel).parent.as_posix())
        self.homes = anchor_homes(design)
        self.unknown: set[str] = set()

    def rel(self, target_rel: str) -> str:
        import posixpath
        return posixpath.relpath(target_rel, self.from_dir)

    def home(self, ident: str) -> str | None:
        key = ident.lower()
        m = SUBSTEP.match(ident) or re.match(r'^WP-(\d{2})$', ident)
        if m:
            files = wp_files(self.design)
            f = files.get(m[1])
            return f'{WP_REL}/{f.name}' if f else None
        cands = self.homes.get(key, [])
        if not cands:
            return None
        if len(cands) == 1:
            return cands[0]
        for pref in PREFERRED_HOMES:
            if pref in cands:
                return pref
        return cands[0]

    def link(self, ident: str) -> str:
        h = self.home(ident)
        if not h:
            self.unknown.add(ident)
            return ident
        return f'[{ident}]({self.rel(h)}#rule-{ident.lower()})'

    def text(self, s: str) -> str:
        """Link every corpus identifier outside existing links; strip code spans around IDs."""
        if not s:
            return ''
        s = s.replace('\r', ' ').replace('\n', ' ').replace('|', '/')
        s = re.sub(r'`([^`]*)`', lambda m: m[1] if CORPUS_ID.search(m[1]) else m[0], s)
        out, pos = [], 0
        spans = [m.span() for m in LINK.finditer(s)]
        for m in CORPUS_ID.finditer(s):
            if any(a <= m.start() < b for a, b in spans):
                continue
            out.append(s[pos:m.start()])
            out.append(self.link(m[0]))
            pos = m.end()
        out.append(s[pos:])
        return ''.join(out)


# ----------------------------------------------------------------------------------------------
# Graph model
# ----------------------------------------------------------------------------------------------

class Graph:
    def __init__(self, design: Path):
        self.design = design
        self.data = load_json(design / GRAPH_REL)
        self.tasks = {t['id']: t for t in self.data['tasks']}
        self.lanes = {l['id']: l for l in self.data['lanes']}
        self.repos = {r['id']: r for r in self.data['repositories']}
        self.subs = {s['id']: s for s in self.data.get('substitutes', [])}
        self.res = {r['id']: r for r in self.data.get('sharedResources', [])}
        self.pobs = {p['id']: p for p in self.data.get('packageObligations', [])}
        self.gates = {g['gate']: g for g in self.data.get('gates', [])}
        self.catalogue = substeps(design)

    def start_edges(self, t):
        return [e for e in t.get('start', [])]

    def complete_edges(self, t):
        return [e for e in t.get('complete', [])]

    def entry(self, tid):
        """Adoption entry task of the owning repository (DLV-22), if any."""
        t = self.tasks[tid]
        a = self.repos.get(t['repo'], {}).get('adoptionTask')
        if not a or a == tid or t.get('kind') == 'adoption' or t['baseline']['state'] == 'accepted':
            return None
        return a

    def starts(self, tid):
        t = self.tasks[tid]
        s = [e['task'] for e in t.get('start', [])]
        a = self.entry(tid)
        return s + ([a] if a and a not in s else [])

    def preds(self, tid):
        t = self.tasks[tid]
        return self.starts(tid) + [e['task'] for e in t.get('complete', [])]

    def succ_map(self):
        succ = defaultdict(set)
        for tid, t in self.tasks.items():
            for e in t.get('start', []) + t.get('complete', []):
                succ[e['task']].add(tid)
        return succ

    def events(self):
        """Event graph (DLV-21): D(t)=delivered, C(t)=complete.

        D(t) needs D(s) for each contract/artifact/design start prerequisite s (and the adoption entry),
        C(s) for each release prerequisite; C(t) needs D(t) and C(s) for each completion prerequisite s.
        """
        adj = defaultdict(set)
        for tid, t in self.tasks.items():
            for e in t.get('start', []):
                adj[('D', tid)].add(('C' if e['type'] == 'release' else 'D', e['task']))
            ent = self.entry(tid)
            if ent:
                adj[('D', tid)].add(('C', ent))
            adj[('C', tid)].add(('D', tid))
            for e in t.get('complete', []):
                adj[('C', tid)].add(('C', e['task']))
        return adj

    def event_order(self):
        adj = self.events()
        nodes = {(k, t) for t in self.tasks for k in ('D', 'C')}
        indeg = {n: 0 for n in nodes}
        rev = defaultdict(set)
        for n, ps in adj.items():
            for p in ps:
                if p in nodes:
                    indeg[n] += 1
                    rev[p].add(n)
        q = deque(sorted(n for n, d in indeg.items() if d == 0))
        order = []
        while q:
            n = q.popleft()
            order.append(n)
            for m in sorted(rev.get(n, ())):
                indeg[m] -= 1
                if indeg[m] == 0:
                    q.append(m)
        stuck = sorted({t for (k, t), d in indeg.items() if d > 0})
        return order, stuck

    def topo(self):
        indeg = {t: 0 for t in self.tasks}
        succ = self.succ_map()
        for tid in self.tasks:
            for p in set(self.preds(tid)):
                if p in self.tasks:
                    indeg[tid] += 1
        q = deque(sorted(t for t, d in indeg.items() if d == 0))
        order = []
        while q:
            n = q.popleft()
            order.append(n)
            for s in sorted(succ.get(n, ())):
                indeg[s] -= 1
                if indeg[s] == 0:
                    q.append(s)
        return order, [t for t, d in indeg.items() if d > 0]

    def ancestors(self, tid, cache={}):
        key = (id(self), tid)
        if key in cache:
            return cache[key]
        seen, stack = set(), list(self.preds(tid))
        while stack:
            p = stack.pop()
            if p in seen or p not in self.tasks:
                continue
            seen.add(p)
            stack.extend(self.preds(p))
        cache[key] = seen
        return seen

    def obligation_map(self):
        m = defaultdict(list)
        for t in self.data['tasks']:
            for o in t.get('obligations', []):
                m[o['ref']].append((t['id'], o.get('part', '')))
        return m


def validate(g: Graph) -> tuple[list[str], list[str]]:
    errors, warnings = [], []
    ids = [t['id'] for t in g.data['tasks']]
    for tid, n in Counter(ids).items():
        if n > 1:
            errors.append(f'duplicate task id {tid}')
    required = ['id', 'title', 'lane', 'repo', 'kind', 'size', 'obligations', 'outcome', 'start',
                'complete', 'writes', 'validation', 'evidence', 'baseline']
    for t in g.data['tasks']:
        tid = t.get('id', '?')
        for f in required:
            if f not in t:
                errors.append(f'{tid}: missing field {f}')
        if not TASK_ID.match(tid):
            errors.append(f'{tid}: invalid task id format')
        if CORPUS_ID.search(t.get('title', '')):
            errors.append(f'{tid}: title contains a corpus identifier; keep identifiers in obligations')
        if t.get('lane') not in g.lanes:
            errors.append(f'{tid}: unknown lane {t.get("lane")}')
        elif not tid.startswith(g.lanes[t['lane']]['prefix'] + '.'):
            errors.append(f'{tid}: prefix does not match lane {t["lane"]}')
        if t.get('repo') not in g.repos:
            errors.append(f'{tid}: unknown repository {t.get("repo")}')
        for r in t.get('alsoTouches', []):
            if r not in g.repos:
                errors.append(f'{tid}: unknown touched repository {r}')
        if t.get('kind') not in KINDS:
            errors.append(f'{tid}: unknown kind {t.get("kind")}')
        if t.get('size') not in SIZES:
            errors.append(f'{tid}: unknown size {t.get("size")}')
        if not t.get('obligations'):
            errors.append(f'{tid}: no obligations')
        for o in t.get('obligations', []):
            ref = o.get('ref', '')
            if SUBSTEP.match(ref):
                if ref not in g.catalogue:
                    errors.append(f'{tid}: obligation {ref} is not an active substep')
            elif POB_ID.match(ref):
                if ref not in g.pobs:
                    errors.append(f'{tid}: unknown package obligation {ref}')
            elif DECISION.match(ref):
                if t.get('kind') not in {'adoption', 'governance'}:
                    errors.append(f'{tid}: decision obligation {ref} is reserved for adoption/governance tasks')
            else:
                errors.append(f'{tid}: invalid obligation reference {ref}')
            if not o.get('part'):
                errors.append(f'{tid}: obligation {ref} lacks part text')
        for kind, allowed in (('start', START_TYPES), ('complete', COMPLETE_TYPES)):
            seen = set()
            for e in t.get(kind, []):
                tgt = e.get('task')
                if e.get('type') not in allowed:
                    errors.append(f'{tid}: {kind} edge to {tgt} has invalid type {e.get("type")}')
                if tgt not in g.tasks:
                    errors.append(f'{tid}: {kind} edge to unknown task {tgt}')
                if tgt == tid:
                    errors.append(f'{tid}: self edge')
                if tgt in seen:
                    errors.append(f'{tid}: duplicate {kind} edge to {tgt}')
                seen.add(tgt)
                if not (e.get('why') or '').strip() or not (e.get('need') or '').strip():
                    errors.append(f'{tid}: {kind} edge to {tgt} lacks need/why')
                if e.get('type') == 'release' and t.get('kind') not in {'release', 'acceptance'}:
                    errors.append(f'{tid}: release edge on a non-release task')
        for s in t.get('substitutes', []):
            if s not in g.subs:
                errors.append(f'{tid}: unknown substitute {s}')
        for sh in t.get('shared', []):
            if sh.get('resource') not in g.res:
                errors.append(f'{tid}: unknown shared resource {sh.get("resource")}')
            if sh.get('mode') not in MODES:
                errors.append(f'{tid}: invalid shared mode {sh.get("mode")}')
        for w in t.get('writes', []):
            repo = w.split(':', 1)[0]
            if ':' not in w or (repo not in g.repos and repo != '*'):
                errors.append(f'{tid}: invalid write scope {w}')
        b = t.get('baseline', {})
        if b.get('state') not in BASELINE:
            errors.append(f'{tid}: invalid baseline state {b.get("state")}')
        if b.get('state') == 'accepted' and not b.get('evidence'):
            errors.append(f'{tid}: accepted baseline without evidence')
    for l in g.lanes.values():
        if l['repo'] not in g.repos and l['repo'] != 'multiple':
            errors.append(f'lane {l["id"]}: unknown repository {l["repo"]}')
    _, stuck = g.event_order()
    if stuck:
        errors.append(f'unsatisfiable prerequisites (deadlock) among {len(stuck)} tasks: {stuck[:12]}')
    # Obligation coverage.
    om = g.obligation_map()
    for sid in g.catalogue:
        if sid not in om:
            errors.append(f'substep {sid} is not mapped to any task')
        elif len(om[sid]) > 1 and any(p.strip().lower() == 'full' for _, p in om[sid]):
            warnings.append(f'substep {sid} mapped by {len(om[sid])} tasks but one claims "full"')
    for pid in g.pobs:
        if pid not in om:
            errors.append(f'package obligation {pid} is not mapped to any task')
    for s in g.pobs.values():
        if not POB_ID.match(s['id']):
            errors.append(f'invalid package obligation id {s["id"]}')
    # Substitutes.
    users = defaultdict(list)
    for t in g.data['tasks']:
        for s in t.get('substitutes', []):
            users[s].append(t['id'])
    for sid, s in g.subs.items():
        if not SUB_ID.match(sid):
            errors.append(f'invalid substitute id {sid}')
        for f in ('standsInFor', 'contract', 'proves', 'realProducer', 'replacedBy', 'realEvidence'):
            if not s.get(f):
                errors.append(f'{sid}: missing {f}')
        rp = s.get('realProducer', [])
        rp = rp if isinstance(rp, list) else [rp]
        rb = s.get('replacedBy')
        for p in rp:
            if p not in g.tasks:
                errors.append(f'{sid}: unknown real producer {p}')
        if rb not in g.tasks:
            errors.append(f'{sid}: unknown replacing task {rb}')
            continue
        anc = g.ancestors(rb)
        for p in rp:
            if p in g.tasks and p != rb and p not in anc:
                errors.append(f'{sid}: replacing task {rb} does not depend on real producer {p}')
        for u in users.get(sid, []):
            if u != rb and u not in anc:
                errors.append(f'{sid}: replacing task {rb} does not depend on consumer {u}')
        if not users.get(sid):
            warnings.append(f'{sid}: substitute not used by any task')
        if g.tasks[rb].get('kind') not in {'integration', 'acceptance', 'release', 'service', 'producer', 'feature'}:
            warnings.append(f'{sid}: replacing task {rb} has kind {g.tasks[rb].get("kind")}')
    # Shared resources.
    for rid, r in g.res.items():
        if not RES_ID.match(rid):
            errors.append(f'invalid shared resource id {rid}')
        if r.get('ownerRepo') not in g.repos and r.get('ownerRepo') not in {'multiple', 'workstation'}:
            errors.append(f'{rid}: unknown owner repository {r.get("ownerRepo")}')
        for f in ('kind', 'owner', 'protocol', 'title'):
            if not r.get(f):
                errors.append(f'{rid}: missing {f}')
    # The same exact file written by two unordered tasks must be a declared shared resource.
    # Different files inside one module directory are ordinary parallel work resolved by Git.
    by_repo = defaultdict(list)
    for t in g.data['tasks']:
        for w in t.get('writes', []):
            repo, path = w.split(':', 1)
            path = path.split(' (', 1)[0].strip()
            if '*' in path or path.endswith('/') or not path:
                continue
            by_repo[repo].append((t['id'], path))
    shared_of = {t['id']: {s['resource'] for s in t.get('shared', [])} for t in g.data['tasks']}
    for repo, items in by_repo.items():
        for i in range(len(items)):
            a, pa = items[i]
            for j in range(i + 1, len(items)):
                b, pb = items[j]
                if a == b:
                    continue
                if pa != pb:
                    continue
                if a in g.ancestors(b) or b in g.ancestors(a):
                    continue
                if shared_of[a] & shared_of[b]:
                    continue
                warnings.append(f'unordered write overlap {a} ~ {b} in {repo}: {pa} / {pb}')
    # Gates.
    for gate, rec in g.gates.items():
        for tid in rec.get('tasks', []):
            if tid not in g.tasks:
                errors.append(f'gate {gate}: unknown task {tid}')
    return errors, warnings


# ----------------------------------------------------------------------------------------------
# Analysis
# ----------------------------------------------------------------------------------------------

def weights(g: Graph):
    return {tid: SIZES[t['size']] for tid, t in g.tasks.items()}


def _event_weights(g: Graph, done):
    return {('D', t): (0 if t in done else SIZES[g.tasks[t]['size']]) for t in g.tasks} | {('C', t): 0 for t in g.tasks}


def critical_path(g: Graph, done: set[str] | None = None):
    """Longest weighted chain on the event graph; a task's work sits on its delivery event."""
    done = done or set()
    order, _ = g.event_order()
    adj = g.events()
    w = _event_weights(g, done)
    finish, prev = {}, {}
    for n in order:
        best, arg = 0, None
        for p in sorted(adj.get(n, ())):
            if finish.get(p, 0) > best:
                best, arg = finish[p], p
        finish[n] = best + w[n]
        prev[n] = arg
    end = max(sorted(finish), key=lambda k: finish[k])
    length = finish[end]
    path = []
    while end:
        if end[0] == 'D' and end[1] not in path:
            path.append(end[1])
        end = prev[end]
    return list(reversed(path)), length


def levels(g: Graph, done: set[str] | None = None):
    """Delivery level: longest chain of unfinished prerequisite deliveries before a task can be delivered."""
    done = done or set()
    order, _ = g.event_order()
    adj = g.events()
    lvl = {}
    for n in order:
        ps = [lvl[p] for p in adj.get(n, ()) if p in lvl]
        base = max(ps) if ps else 0
        lvl[n] = base + (1 if n[0] == 'D' and n[1] not in done else 0)
    return {t: lvl[('D', t)] for t in g.tasks}


def simulate(g: Graph, workers: int, done: set[str] | None = None):
    """List scheduling on the event graph. A worker is busy only while a task's own work runs;
    completion prerequisites delay completion, not the worker. Priority: longest remaining path.
    Repository merge, review and CI capacity are not modelled. Returns makespan in size units."""
    done = set(done or set())
    adj = g.events()
    w = {t: SIZES[g.tasks[t]['size']] for t in g.tasks}
    succ = defaultdict(set)
    for n, ps in adj.items():
        for p in ps:
            succ[p].add(n)
    order, _ = g.event_order()
    rem = {}
    for n in reversed(order):
        rem[n] = (w[n[1]] if n[0] == 'D' else 0) + max((rem[s] for s in succ.get(n, ())), default=0)
    reached = set()
    for t in done:
        reached.add(('D', t)); reached.add(('C', t))
    time, running, heap, queued = 0.0, [], [], set()

    def settle():
        changed = True
        while changed:
            changed = False
            for t in g.tasks:
                c = ('C', t)
                if c not in reached and ('D', t) in reached and adj[c] <= reached:
                    reached.add(c); changed = True
            for t in g.tasks:
                d = ('D', t)
                if d in reached or t in queued:
                    continue
                if adj.get(d, set()) <= reached:
                    heapq.heappush(heap, (-rem[d], t)); queued.add(t)

    settle()
    while len(reached) < 2 * len(g.tasks):
        while heap and (workers <= 0 or len(running) < workers):
            _, t = heapq.heappop(heap)
            heapq.heappush(running, (time + w[t], t))
        if not running:
            raise Fail('simulation deadlock (unsatisfiable prerequisites)')
        end, t = heapq.heappop(running)
        time = end
        reached.add(('D', t))
        settle()
    return time


def old_model_metrics(design: Path):
    """Depth of the retired WP-level graph and the retired serial substep count."""
    seq = (design / 'docs/planning/implementation-sequence.md').read_text(encoding='utf-8')
    return {'substeps': len(substeps(design))}


def analysis(g: Graph, worker_counts=(1, 2, 4, 8, 16, 32, 64, 0)):
    done = {tid for tid, t in g.tasks.items() if t['baseline']['state'] == 'accepted'}
    total = sum(SIZES[t['size']] for tid, t in g.tasks.items() if tid not in done)
    path, length = critical_path(g, done)
    lvl = levels(g, done)
    width = Counter(v for tid, v in lvl.items() if tid not in done)
    sims = {}
    for wk in worker_counts:
        sims['unbounded' if wk == 0 else str(wk)] = simulate(g, wk, done)
    edge_types = Counter()
    for t in g.tasks.values():
        for e in t.get('start', []):
            edge_types[e['type']] += 1
        for e in t.get('complete', []):
            edge_types['integration(completion)'] += 1
    adopted = done | {tid for tid, t in g.tasks.items() if t.get('kind') == 'adoption'}
    ready = [tid for tid, t in g.tasks.items() if tid not in done and t.get('kind') != 'adoption'
             and all(p in adopted for p in g.starts(tid))]
    ready_width = len(ready)
    return {
        'tasks': len(g.tasks), 'acceptedBaseline': len(done), 'remainingWork': total,
        'criticalPath': path, 'criticalPathLength': length,
        'maxLevel': max((v for tid, v in lvl.items() if tid not in done), default=0) + 1,
        'levelWidths': dict(sorted(width.items())),
        'maxLevelWidth': max(width.values()) if width else 0,
        'simulatedMakespan': sims, 'edgeTypes': dict(edge_types),
        'initialReady': sorted(ready),
    }


# ----------------------------------------------------------------------------------------------
# Views
# ----------------------------------------------------------------------------------------------

def md_escape(s: str) -> str:
    return (s or '').replace('|', '/').replace('\n', ' ').strip()


def task_link(g: Graph, tid: str, from_rel: str) -> str:
    import posixpath
    lane = g.tasks[tid]['lane']
    target = f'{DELIVERY_REL}/lanes/{lane}.md'
    rel = posixpath.relpath(target, str(Path(from_rel).parent.as_posix()))
    if target == from_rel:
        rel = ''
    return f'[{tid}]({rel}#{slug(tid)})'


def generated_header(from_rel: str) -> str:
    import posixpath
    graph = posixpath.relpath(GRAPH_REL, str(Path(from_rel).parent.as_posix()))
    model = posixpath.relpath(f'{DELIVERY_REL}/README.md', str(Path(from_rel).parent.as_posix()))
    return (f'> Generated from [the delivery graph]({graph}) by Plan `tools/delivery.py`; do not edit by hand. '
            f'Rules and definitions: [delivery model]({model}).\n')


def render_lane(g: Graph, lane: dict) -> str:
    rel = f'{DELIVERY_REL}/lanes/{lane["id"]}.md'
    L = Linker(g.design, rel)
    succ = g.succ_map()
    tasks = [t for t in g.data['tasks'] if t['lane'] == lane['id']]
    out = [f'# {lane["title"]} — delivery tasks', '', generated_header(rel)]
    out.append(L.text(lane.get('description', '')))
    out.append('')
    repos = sorted({t['repo'] for t in tasks})
    out.append(f'Tasks: {len(tasks)} · Owning repositories: {", ".join(repos)} · '
               f'Integration owner(s): {", ".join(g.repos[r]["integrationOwner"] for r in repos)}')
    out.append('')
    out.append('| Task | Title | Kind | Size | Start prerequisites | Baseline |')
    out.append('|---|---|---|---|---|---|')
    for t in tasks:
        pre = ', '.join(f'{task_link(g, e["task"], rel)} ({e["type"]})' for e in t['start']) or 'none'
        out.append(f'| {task_link(g, t["id"], rel)} | {md_escape(t["title"])} | {t["kind"]} | {t["size"]} | {pre} | '
                   f'{t["baseline"]["state"]} |')
    out.append('')
    out.append('## Tasks')
    out.append('')
    for t in tasks:
        out.append(f'<a id="{slug(t["id"])}"></a>')
        out.append('')
        out.append(f'### {t["id"]} — {md_escape(t["title"])}')
        out.append('')
        out.append(f'**Outcome.** {L.text(t["outcome"])}')
        out.append('')
        out.append('| Field | Value |')
        out.append('|---|---|')
        repo = g.repos[t['repo']]
        touches = ', '.join(t.get('alsoTouches', []))
        out.append(f'| Owning repository | {t["repo"]} (`{repo["root"]}`); integration owner: {repo["integrationOwner"]}'
                   + (f'; also touches {touches}' if touches else '') + ' |')
        out.append(f'| Kind / size | {t["kind"]} / {t["size"]}' + (' · early risk proof' if t.get('earlyRiskProof') else '') + ' |')
        obl = '<br>'.join(f'{obligation_link(g, L, o["ref"])} — {L.text(o["part"])}' for o in t['obligations'])
        out.append(f'| Obligations | {obl} |')
        if t.get('provides'):
            out.append(f'| Provides | {L.text("; ".join(t["provides"]))} |')
        st = '<br>'.join(f'**{e["type"]}** {task_link(g, e["task"], rel)} — {L.text(e["need"])}. *Why:* {L.text(e["why"])}'
                         for e in t['start']) or 'none'
        out.append(f'| Start prerequisites | {st} |')
        ent = g.entry(t['id'])
        if ent:
            out.append(f'| Entry condition | {task_link(g, ent, rel)} — adoption of the owning repository is complete ([DLV-22](../README.md#rule-dlv-22)) |')
        cp = '<br>'.join(f'**{e["type"]}** {task_link(g, e["task"], rel)} — {L.text(e["need"])}. *Why:* {L.text(e["why"])}'
                         for e in t['complete']) or 'none'
        out.append(f'| Completion prerequisites | {cp} |')
        down = sorted(succ.get(t['id'], ()))
        out.append(f'| Unblocks | {", ".join(task_link(g, d, rel) for d in down) or "none"} |')
        if t.get('substitutes'):
            import posixpath
            srel = posixpath.relpath(f'{DELIVERY_REL}/substitutes.md', str(Path(rel).parent.as_posix()))
            subs = ', '.join(f'[{s}]({srel}#{s.lower()})' for s in t['substitutes'])
            out.append(f'| Permitted substitutes | {subs} |')
        out.append(f'| Write scope | {"<br>".join("`" + w + "`" for w in t["writes"])} |')
        if t.get('shared'):
            import posixpath
            rrel = posixpath.relpath(f'{DELIVERY_REL}/shared-resources.md', str(Path(rel).parent.as_posix()))
            sh = ', '.join(f'[{s["resource"]}]({rrel}#{s["resource"].lower()}) ({s["mode"]})' for s in t['shared'])
            out.append(f'| Shared resources | {sh} |')
        out.append(f'| Validation | {L.text(t["validation"])} |')
        out.append(f'| Completion evidence | {L.text(t["evidence"])} |')
        b = t['baseline']
        btxt = b['state'] + (f' — {L.text(b.get("evidence", ""))}' if b.get('evidence') else '') + \
            (f' {L.text(b.get("notes", ""))}' if b.get('notes') else '')
        out.append(f'| Baseline (unreviewed unless accepted) | {btxt} |')
        if t.get('notes'):
            out.append(f'| Notes | {L.text(t["notes"])} |')
        out.append('')
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(out).rstrip() + '\n'


def obligation_link(g: Graph, L: Linker, ref: str) -> str:
    if SUBSTEP.match(ref) or DECISION.match(ref):
        return L.link(ref)
    m = POB_ID.match(ref)
    p = g.pobs[ref]
    return f'{L.link("WP-" + m[1])} {L.text(p["title"])}'


def render_traceability(g: Graph) -> str:
    rel = f'{DELIVERY_REL}/traceability.md'
    L = Linker(g.design, rel)
    om = g.obligation_map()
    out = ['# Obligation Traceability', '', generated_header(rel),
           'Every active numbered substep and every package-level obligation maps to the delivery tasks that '
           'satisfy it. An obligation is satisfied only when every mapped task is complete with its recorded '
           'evidence; a mapped part never substitutes for the whole.', '']
    by_wp = defaultdict(list)
    for sid, s in g.catalogue.items():
        by_wp[s['wp']].append(sid)
    for wp in sorted(by_wp):
        f = wp_files(g.design)[wp]
        title = next((ln[2:].strip() for ln in f.read_text(encoding='utf-8').splitlines() if ln.startswith('# ')), wp)
        out.append(f'## {L.link("WP-" + wp)} — {md_escape(title.split("—", 1)[-1].strip())}')
        out.append('')
        out.append('| Obligation | Title | Delivery tasks (part) |')
        out.append('|---|---|---|')
        for sid in sorted(by_wp[wp]):
            tasks = '<br>'.join(f'{task_link(g, tid, rel)} ({L.text(part)})' for tid, part in om.get(sid, []))
            out.append(f'| {L.link(sid)} | {md_escape(g.catalogue[sid]["title"])} | {tasks} |')
        pobs = [p for p in g.pobs.values() if p['id'].startswith(f'WP-{wp}:')]
        for p in pobs:
            tasks = '<br>'.join(f'{task_link(g, tid, rel)} ({L.text(part)})' for tid, part in om.get(p['id'], []))
            out.append(f'| {L.link("WP-" + wp)} package obligation | {L.text(p["title"])} | {tasks} |')
        out.append('')
    out.append('## Gates')
    out.append('')
    out.append('| Gate | Contribution | Delivery tasks |')
    out.append('|---|---|---|')
    for gate in sorted(g.gates):
        rec = g.gates[gate]
        glabel = L.link(gate) if (L.home(gate) or CORPUS_ID.fullmatch(gate)) else f'[{gate}]({L.rel("docs/experience/03-state-and-acceptance.md")})'
        out.append(f'| {glabel} | {L.text(rec.get("contribution", ""))} | '
                   f'{", ".join(task_link(g, t, rel) for t in rec.get("tasks", []))} |')
    out.append('')
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(out).rstrip() + '\n'


def render_substitutes(g: Graph) -> str:
    rel = f'{DELIVERY_REL}/substitutes.md'
    L = Linker(g.design, rel)
    users = defaultdict(list)
    for t in g.data['tasks']:
        for s in t.get('substitutes', []):
            users[s].append(t['id'])
    out = ['# Substitutes and Real Replacement', '', generated_header(rel),
           'A substitute implements an authoritative contract so that a consumer can start before its real '
           'producer exists. Its checks prove only what is stated here. The replacing task removes runtime '
           'registration of the substitute and records the real evidence; retained regression fixtures stay '
           'test-only.', '',
           '| Substitute | Stands in for | Real producer | Replaced by | Used by |', '|---|---|---|---|---|']
    for sid in sorted(g.subs):
        s = g.subs[sid]
        rp = s['realProducer'] if isinstance(s['realProducer'], list) else [s['realProducer']]
        out.append(f'| [{sid}](#{sid.lower()}) | {L.text(s["standsInFor"])} | '
                   f'{", ".join(task_link(g, p, rel) for p in rp)} | {task_link(g, s["replacedBy"], rel)} | '
                   f'{", ".join(task_link(g, u, rel) for u in users.get(sid, []))} |')
    out.append('')
    for sid in sorted(g.subs):
        s = g.subs[sid]
        out.append(f'### {sid}')
        out.append('')
        out.append('| Field | Value |')
        out.append('|---|---|')
        out.append(f'| Stands in for | {L.text(s["standsInFor"])} |')
        out.append(f'| Authoritative contract | {L.text(s["contract"])} |')
        out.append(f'| What its checks prove | {L.text(s["proves"])} |')
        out.append(f'| What it does not prove | {L.text(s.get("doesNotProve", "Any real runtime, provider, device, integration or commercial behavior."))} |')
        rp = s['realProducer'] if isinstance(s['realProducer'], list) else [s['realProducer']]
        out.append(f'| Real producer | {", ".join(task_link(g, p, rel) for p in rp)} |')
        out.append(f'| Removes runtime substitution | {task_link(g, s["replacedBy"], rel)} |')
        out.append(f'| Real evidence still required | {L.text(s["realEvidence"])} |')
        if s.get('origin'):
            out.append(f'| Origin | {L.text(s["origin"])} |')
        out.append('')
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(out).rstrip() + '\n'


def render_resources(g: Graph) -> str:
    rel = f'{DELIVERY_REL}/shared-resources.md'
    L = Linker(g.design, rel)
    touch = defaultdict(list)
    for t in g.data['tasks']:
        for s in t.get('shared', []):
            touch[s['resource']].append((t['id'], s['mode']))
    out = ['# Shared Resources and Write Ownership', '', generated_header(rel),
           'Each shared file, registry, sequence, environment, key or pointer has exactly one owning role. '
           'Tasks declare how they touch it; the owner applies the protocol. Independent worktrees do not '
           'remove semantic conflicts, so these declarations are part of task readiness and merge review.', '']
    out.append('| Resource | Kind | Owner | Tasks (mode) |')
    out.append('|---|---|---|---|')
    for rid in sorted(g.res):
        r = g.res[rid]
        tasks = ', '.join(f'{task_link(g, t, rel)} ({m})' for t, m in touch.get(rid, []))
        out.append(f'| [{rid}](#{rid.lower()}) | {r["kind"]} | {L.text(r["owner"])} | {tasks} |')
    out.append('')
    for rid in sorted(g.res):
        r = g.res[rid]
        out.append(f'<a id="{rid.lower()}"></a>')
        out.append('')
        out.append(f'### {rid} — {md_escape(r["title"])}')
        out.append('')
        out.append(f'Repository: {r["ownerRepo"]} · Kind: {r["kind"]} · Owner: {L.text(r["owner"])}')
        out.append('')
        out.append(f'**Protocol.** {L.text(r["protocol"])}')
        out.append('')
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(out).rstrip() + '\n'


def render_analysis(g: Graph) -> str:
    rel = f'{DELIVERY_REL}/schedule-analysis.md'
    L = Linker(g.design, rel)
    a = analysis(g)
    out = ['# Schedule Analysis', '', generated_header(rel)]
    out.append(L.text(g.data.get('analysisPreamble', '')))
    out.append('')
    out.append('## Structural facts (computed from the graph)')
    out.append('')
    out.append('| Measure | Value |')
    out.append('|---|---|')
    out.append(f'| Delivery tasks | {a["tasks"]} ({a["acceptedBaseline"]} carried as accepted baseline) |')
    et = ', '.join(f'{k} {v}' for k, v in sorted(a['edgeTypes'].items()))
    out.append(f'| Dependency edges by type | {et} |')
    out.append(f'| Remaining work (size units: S=1, M=2, L=4, XL=8) | {a["remainingWork"]} |')
    out.append(f'| Longest dependency chain (levels) | {a["maxLevel"]} |')
    out.append(f'| Widest level (tasks whose longest prerequisite chain has equal length) | {a["maxLevelWidth"]} |')
    out.append(f'| Critical path length (size units) | {a["criticalPathLength"]} |')
    out.append(f'| Retired model | {len(g.catalogue)} numbered substeps advanced one at a time from a single Current task |')
    out.append('')
    out.append('## Work by lane')
    out.append('')
    out.append('| Lane | Tasks | Size units | Owning repositories |')
    out.append('|---|---|---|---|')
    for lane in g.data['lanes']:
        lt = [t for t in g.data['tasks'] if t['lane'] == lane['id']]
        if lt:
            out.append(f'| [{md_escape(lane["title"])}](lanes/{lane["id"]}.md) | {len(lt)} | {sum(SIZES[t["size"]] for t in lt)} | '
                       f'{", ".join(sorted({t["repo"] for t in lt}))} |')
    out.append('')
    out.append('## Critical path')
    out.append('')
    out.append('| # | Task | Size | Title |')
    out.append('|---|---|---|---|')
    for i, tid in enumerate(a['criticalPath'], 1):
        t = g.tasks[tid]
        out.append(f'| {i} | {task_link(g, tid, rel)} | {t["size"]} | {md_escape(t["title"])} |')
    out.append('')
    out.append('## Level widths')
    out.append('')
    out.append('| Level | Tasks |')
    out.append('|---|---|')
    for k, v in a['levelWidths'].items():
        out.append(f'| {k} | {v} |')
    out.append('')
    out.append('## Simulated makespan (unmeasured estimate)')
    out.append('')
    out.append(L.text(g.data.get('simulationAssumptions', '')))
    out.append('')
    out.append('| Workers | Makespan (size units) | Estimated speed-up over one worker |')
    out.append('|---|---|---|')
    one = a['simulatedMakespan']['1']
    for k, v in a['simulatedMakespan'].items():
        out.append(f'| {k} | {v:g} | {one / v:.1f}× |')
    out.append('')
    out.append('## Provisional initial ready set')
    out.append('')
    out.append(L.text(g.data.get('readySetNote', '')))
    out.append('')
    out.append(', '.join(task_link(g, t, rel) for t in a['initialReady']))
    out.append('')
    if g.data.get('bottlenecks'):
        out.append('## Remaining serial dependencies and bottlenecks')
        out.append('')
        for b in g.data['bottlenecks']:
            out.append(f'- **{md_escape(b["title"])}.** {L.text(b["text"])}')
        out.append('')
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(out).rstrip() + '\n'


def render_wp_block(g: Graph, wp: str, rel: str) -> str:
    L = Linker(g.design, rel)
    mapped = defaultdict(list)
    for t in g.data['tasks']:
        for o in t['obligations']:
            m = SUBSTEP.match(o['ref']) or POB_ID.match(o['ref'])
            if m and m[1] == wp:
                mapped[t['id']].append(o)
    own = sorted(mapped, key=lambda x: (g.tasks[x]['lane'], x))
    lines = [BEGIN, '',
             'Scheduling is task-level under [P2-018](../../decisions/phase-2-specification-decisions.md#rule-p2-018). '
             'This package is an obligation set; it is satisfied when every task below is complete with its evidence. '
             'Prerequisites are typed task edges, never "all upstream packages complete".', '',
             '| Delivery task | Satisfies | Start prerequisites outside this package |', '|---|---|---|']
    own_set = set(own)
    for tid in own:
        t = g.tasks[tid]
        sat = '<br>'.join(f'{obligation_link(g, L, o["ref"])} ({L.text(o["part"])})' for o in mapped[tid])
        ext = ', '.join(f'{task_link(g, e["task"], rel)} ({e["type"]})' for e in t['start'] if e['task'] not in own_set) or 'none'
        lines.append(f'| {task_link(g, tid, rel)} | {sat} | {ext} |')
    succ = g.succ_map()
    consumers = sorted({s for tid in own for s in succ.get(tid, ()) if s not in own_set})
    lines.append('')
    lines.append('**Consumers outside this package:** ' + (', '.join(task_link(g, c, rel) for c in consumers) or 'none') + '.')
    lines.append('')
    lines.append(END)
    if L.unknown:
        raise Fail(f'{rel}: unresolved identifiers {sorted(L.unknown)}')
    return '\n'.join(lines)


def splice(text: str, block: str) -> str:
    if BEGIN in text:
        pre, rest = text.split(BEGIN, 1)
        _, post = rest.split(END, 1)
        return pre + block + post
    raise Fail('missing generated delivery block markers')


def render_prompts(g: Graph, design: Path, plan: Path, only_lane: str | None = None) -> str:
    design_win = g.data['paths']['design']
    plan_win = g.data['paths']['plan']
    succ = g.succ_map()
    title = f'# ArcForges delivery task prompts — {g.lanes[only_lane]["title"]}' if only_lane else '# ArcForges delivery task prompts'
    out = [title, '',
           'Generated from Design `docs/planning/delivery/delivery-graph.json` by `tools/delivery.py`; do not edit by hand.',
           'Each block is self-contained. Claim a task only when `python tools/delivery.py ready --claims` lists it,',
           'then follow `arcforges-implementation.md`. Tasks are ordered by lane for reading; the order is not a schedule.', '']
    for lane in g.data['lanes']:
        if only_lane and lane['id'] != only_lane:
            continue
        tasks = [t for t in g.data['tasks'] if t['lane'] == lane['id']]
        if not tasks:
            continue
        out.append(f'## {lane["title"]}')
        out.append('')
        for t in tasks:
            repo = g.repos[t['repo']]
            b = ['```text', f'Execute ArcForges delivery task {t["id"]} — {t["title"]}.', '']
            b.append(f'Task record: {design_win}\\docs\\planning\\delivery\\lanes\\{t["lane"]}.md (anchor {slug(t["id"])}).')
            b.append(f'Delivery rules: {design_win}\\docs\\planning\\delivery\\README.md; execution: {plan_win}\\arcforges-implementation.md.')
            b.append(f'Owning repository: {repo["root"]} (integration owner: {repo["integrationOwner"]}).'
                     + (f' Also touches: {", ".join(t["alsoTouches"])}.' if t.get('alsoTouches') else ''))
            b.append(f'Kind/size: {t["kind"]}/{t["size"]}. Baseline: {t["baseline"]["state"]}.')
            b.append(f'Outcome: {t["outcome"]}')
            b.append('')
            b.append('Obligations (authoritative definitions; satisfy exactly these parts and their tests/gates):')
            for o in t['obligations']:
                if SUBSTEP.match(o['ref']):
                    f = wp_files(design)[o['ref'][3:5]].name
                    b.append(f'- {o["ref"]} ({o["part"]}): {design_win}\\docs\\planning\\work-packages\\{f}, anchor rule-{o["ref"].lower()}')
                elif DECISION.match(o['ref']):
                    b.append(f'- {o["ref"]} ({o["part"]}): {design_win}\\docs\\decisions\\phase-2-specification-decisions.md, anchor rule-{o["ref"].lower()}')
                    continue
                else:
                    p = g.pobs[o['ref']]
                    f = wp_files(design)[o['ref'][3:5]].name
                    b.append(f'- {o["ref"]} {p["title"]} ({o["part"]}): {design_win}\\docs\\planning\\work-packages\\{f}'
                             + (f', {p["section"]}' if p.get('section') else ', package-level obligation'))
            b.append('')
            ent = g.entry(t['id'])
            if ent:
                b.append(f'Entry condition: {ent} (adoption of the owning repository) is complete in the Plan ledger.')
            b.append('Start prerequisites (before claiming, each contract/artifact/design prerequisite must be delivered or complete'
                     ' and each release prerequisite complete in the Plan ledger; DLV-24):')
            for e in t['start'] or []:
                b.append(f'- [{e["type"]}] {e["task"]}: {e["need"]}')
            if not t['start']:
                b.append('- none')
            b.append('Completion prerequisites (may start earlier; cannot complete before these are complete):')
            for e in t['complete'] or []:
                b.append(f'- [{e["type"]}] {e["task"]}: {e["need"]}')
            if not t['complete']:
                b.append('- none')
            b.append('')
            b.append('Permitted write scope: ' + '; '.join(t['writes']))
            if t.get('shared'):
                b.append('Shared resources (follow the owner protocol): ' + '; '.join(
                    f'{s["resource"]} ({s["mode"]}): {g.res[s["resource"]]["protocol"]}' for s in t['shared']))
            if t.get('substitutes'):
                b.append('Permitted substitutes (never real integration evidence): ' + '; '.join(
                    f'{s}: {g.subs[s]["proves"]} Real producer {g.subs[s]["realProducer"]}; removed by {g.subs[s]["replacedBy"]}'
                    for s in t['substitutes']))
            down = sorted(succ.get(t['id'], ()))
            if down:
                b.append('Unblocks: ' + ', '.join(down))
            b.append('')
            b.append(f'Validation (P2-017; no macOS/hosted runtime, device, GUI, browser E2E, live-service, inference or installed-consumer CI): {t["validation"]}')
            b.append(f'Completion evidence for the ledger: {t["evidence"]}')
            if t.get('notes'):
                b.append(f'Notes: {t["notes"]}')
            b.append('```')
            out.extend(b)
            out.append('')
    return '\n'.join(out).rstrip() + '\n'


def render_index(g: Graph) -> str:
    """Plan list.md: compact index of every task with its prompt file."""
    out = ['# ArcForges delivery task list', '',
           'Generated from Design `docs/planning/delivery/delivery-graph.json` by `tools/delivery.py`; do not edit by hand.',
           'There is no Current task. Any number of workers may execute different ready tasks at the same time.',
           'Find ready tasks with `python tools/delivery.py ready`, claim one as described in `arcforges-implementation.md`,',
           'and paste its self-contained prompt from the lane file linked below. The order here is for reading only.', '',
           f'Tasks: {len(g.tasks)} in {sum(1 for l in g.lanes if any(t["lane"] == l for t in g.tasks.values()))} lanes.', '']
    for lane in g.data['lanes']:
        tasks = [t for t in g.data['tasks'] if t['lane'] == lane['id']]
        if not tasks:
            continue
        out += [f'## {lane["title"]} — [prompts](tasks/{lane["id"]}.md)', '',
                '| Task | Repository | Size | Start prerequisites | Title |', '|---|---|---|---|---|']
        for t in tasks:
            pre_list = [e['task'] for e in t['start']]
            ent = g.entry(t['id'])
            if ent:
                pre_list.append(f'{ent} (adoption)')
            pre = ', '.join(pre_list) or '—'
            out.append(f'| {t["id"]} | {t["repo"]} | {t["size"]} | {pre} | {md_escape(t["title"])} |')
        out.append('')
    return '\n'.join(out).rstrip() + '\n'


def views(g: Graph, design: Path, plan: Path) -> dict[Path, str]:
    files = {}
    for lane in g.data['lanes']:
        if any(t['lane'] == lane['id'] for t in g.data['tasks']):
            files[design / DELIVERY_REL / 'lanes' / f'{lane["id"]}.md'] = render_lane(g, lane)
    files[design / DELIVERY_REL / 'traceability.md'] = render_traceability(g)
    files[design / DELIVERY_REL / 'substitutes.md'] = render_substitutes(g)
    files[design / DELIVERY_REL / 'shared-resources.md'] = render_resources(g)
    files[design / DELIVERY_REL / 'schedule-analysis.md'] = render_analysis(g)
    for wp, p in wp_files(design).items():
        text = p.read_text(encoding='utf-8')
        if BEGIN not in text:
            continue
        rel = p.relative_to(design).as_posix()
        files[p] = splice(text, render_wp_block(g, wp, rel))
    files[plan / 'list.md'] = render_index(g)
    for lane in g.data['lanes']:
        if any(t['lane'] == lane['id'] for t in g.data['tasks']):
            files[plan / 'tasks' / f'{lane["id"]}.md'] = render_prompts(g, design, plan, lane['id'])
    return files


# ----------------------------------------------------------------------------------------------
# Ledger and readiness
# ----------------------------------------------------------------------------------------------

def ledger(plan: Path) -> dict[str, str]:
    out = {}
    for p in sorted((plan / 'ledger' / 'tasks').glob('*.md')):
        head = p.read_text(encoding='utf-8').split('\n---', 1)[0]
        m_task = re.search(r'^task:\s*(\S+)\s*$', head, re.M)
        m_status = re.search(r'^status:\s*(\S+)\s*$', head, re.M)
        if m_task and m_status:
            out[m_task[1]] = m_status[1]
    return out


def claimed(plan: Path, grace_hours: int = 1) -> set[str]:
    """Task ids currently owned through a claim branch (DLV-26/DLV-27).

    Fetches claims/* into refs/remotes/origin/claims/* (read-only for the remote) and reads each
    branch tip's claim.json. A claim is taken while its state is claimed or blocked and its lease,
    plus a clock-skew grace period, has not expired; delivered and complete claims are taken too.
    Released claims and expired leases are available for re-claim or takeover by a fast-forward append.
    """
    import datetime
    import subprocess
    fetch = ['git', '-C', str(plan), 'fetch', '--quiet', 'origin', '+refs/heads/claims/*:refs/remotes/origin/claims/*']
    if subprocess.run(fetch).returncode != 0:
        raise Fail('network operation failed: ' + ' '.join(fetch[3:]) + ' (report it and stop; do not retry or change networking)')
    refs = subprocess.run(['git', '-C', str(plan), 'for-each-ref', '--format=%(refname:strip=4)',
                           'refs/remotes/origin/claims/'], capture_output=True, text=True, check=True).stdout.split()
    now = datetime.datetime.now(datetime.timezone.utc)
    taken = set()
    for name in refs:
        shown = subprocess.run(['git', '-C', str(plan), 'show', f'refs/remotes/origin/claims/{name}:claim.json'],
                               capture_output=True, text=True)
        if shown.returncode != 0:
            taken.add(name.upper())  # unreadable claim: treat as taken and let a human resolve it
            continue
        try:
            rec = json.loads(shown.stdout)
            state = rec.get('state', 'claimed')
            lease = datetime.datetime.fromisoformat(rec.get('leaseUntil', '').replace('Z', '+00:00'))
        except (ValueError, AttributeError):
            taken.add(name.upper())
            continue
        if state in {'delivered', 'complete'}:
            taken.add(name.upper())
        elif state in {'claimed', 'blocked'} and lease + datetime.timedelta(hours=grace_hours) > now:
            taken.add(name.upper())
    return taken


def ready(g: Graph, plan: Path, lane: str | None, with_claims: bool = False):
    """Readiness under DLV-22/DLV-24: contract, artifact and design prerequisites need the target delivered
    (or complete/inherited); release prerequisites and the adoption entry need it complete (or inherited)."""
    status = ledger(plan)
    delivered = {t for t, s in status.items() if s in {'delivered', 'complete', 'inherited'}}
    complete = {t for t, s in status.items() if s in {'complete', 'inherited'}}
    taken = claimed(plan) if with_claims else set()
    rows = []
    for tid, t in g.tasks.items():
        if tid in delivered or status.get(tid) == 'superseded' or tid in taken:
            continue
        if t['baseline']['state'] == 'accepted':
            continue  # recorded as inherited by the adoption stage, never re-executed
        if lane and t['lane'] != lane:
            continue
        ok = all((e['task'] in complete) if e['type'] == 'release' else (e['task'] in delivered) for e in t['start'])
        ent = g.entry(tid)
        if ent and ent not in complete:
            ok = False
        if ok:
            rows.append(tid)
    return rows, status


# ----------------------------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('command', choices=['check', 'generate', 'analyze', 'ready'])
    ap.add_argument('--design', default=str(PLAN_ROOT.parent / 'ArcForges-Design-B'))
    ap.add_argument('--plan', default=str(PLAN_ROOT))
    ap.add_argument('--lane')
    ap.add_argument('--claims', action='store_true', help='exclude tasks owned by a live claim branch (fetches claims/* read-only)')
    args = ap.parse_args()
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')
    design, plan = Path(args.design).resolve(), Path(args.plan).resolve()
    try:
        g = Graph(design)
        errors, warnings = validate(g)
        if args.command in {'check', 'generate'}:
            for w in warnings:
                print('warning:', w)
            if errors:
                for e in errors:
                    print('error:', e)
                raise Fail(f'{len(errors)} graph errors')
            files = views(g, design, plan)
            if args.command == 'generate':
                for p, text in files.items():
                    p.parent.mkdir(parents=True, exist_ok=True)
                    p.write_text(text, encoding='utf-8', newline='\n')
                print(f'generated {len(files)} files')
            else:
                stale = [p for p, text in files.items() if not p.exists() or p.read_text(encoding='utf-8') != text]
                for p in stale:
                    print('stale view:', p)
                if stale:
                    raise Fail(f'{len(stale)} generated views are stale; run generate')
                print(f'check passed: {len(g.tasks)} tasks, {len(files)} views current, {len(warnings)} warnings')
        elif args.command == 'analyze':
            if errors:
                raise Fail(f'{len(errors)} graph errors; run check')
            print(json.dumps(analysis(g), indent=1))
        elif args.command == 'ready':
            rows, status = ready(g, plan, args.lane, args.claims)
            for tid in sorted(rows):
                print(f'{tid}\t{g.tasks[tid]["repo"]}\t{g.tasks[tid]["title"]}')
            print(f'{len(rows)} tasks satisfy the start rule' + ('' if args.claims else '; run with --claims to exclude tasks held by a live claim'))
    except Fail as exc:
        print('FAILED:', exc)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
